version: 0.0
os: linux
files:
  - source: /frontend/build/
    destination: /var/www/html/frontend/

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 300
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_httpd.sh
      timeout: 300
